### ISSUE TITLE
List all needed data in the documentation

### ISSUE THREAD

**Issue by hungrymonkey** [hackla-engage/engage-warc-test#15]
We need to create a new markdown to show newcomers which data embedded in html elements are needed to be extracted.

Required elements will be tracked here until everything is documented.

**Comment by hungrymonkey** [comment]
current snapshot for agenda 3610
```

GET /api/agendas/item/3610/

{
    "id": 1238,
    "recommendations": [
        {
            "id": 1238,
            "recommendation": [
                "Staff recommends that City Council authorize the City Manager to negotiate and execute a second amendment and reinstatement of agreement #4553 in the amount of $181,000 with Bear Communications, Inc., a California corporation, for extension of an antenna site lease. The change would result in a 20-year amended agreement with a total contract amount not to exceed $507,000, with future year funding contingent on Council budget approval."
            ],
            "agenda_item": 1238
        }
    ],
    "title": "Approval of Big Blue Bus (BBB) lease extension with Bearcomm for Hollywood Hills Radio Site",
    "department": "Big Blue Bus, Finance & Administrative Services",
    "body": [
        "Summary",
        "In 2005, Big Blue Bus (BBB) entered into an agreement with Advanced Electronics, the predecessor-in-interest to Bear Communications, Inc., for the sublease of an antenna site in the Hollywood Hills to install radio transponders to allow BBB to communicate with its vehicles across its service area. The antenna site is the only location available to adequately provide data signals to BBB’s operational systems. Staff recommends that City Council authorize the City Manager to negotiate and execute a second amendment and reinstatement to the Antenna Site Sublease Agreement #4553 with Bear Communications, Inc. for one year with four additional one-year options, and for additional compensation in an amount not to exceed $181,000.  The amount for the first year of the extension would be $32,600. This would result in a 20-year amended agreement with a new total contract amount not to exceed $507,000, with future year funding contingent on Council budget approval. This is a sole source procurement due to Federal Communications Commission (FCC) regulations regarding the BBB’s ability to transmit radio signals.",
        "Discussion",
        "BBB implemented an Advanced Fleet Management System (AFMS) in 2003 for transit vehicles that provides Computer Aided Dispatch/Automatic Vehicle Location (CAD/AVL) data.  In support of the AFMS, the City entered into a sublease with Advanced Electronics, the predecessor-in-interest to Bear Communications, Inc. on February 8, 2005 to install radio transponders at the Hollywood Hills antenna site. Currently, the Hollywood Hills antenna site houses BBB’s radio equipment which provides support for the AFMS, voice communication (two-way radio between buses and dispatch), data for real-time signage and customer trip-planning applications such as NextBus, Transit, and Google Transit, and vehicle tracking. BBB utilizes these radio frequencies to communicate with vehicles, collect data to locate and monitor those vehicles, and provide real-time scheduling information to many other transit agencies and systems.  The data provides real-time information to customers on bus arrival information through various applications, providing an advanced customer service experience to the community. The sublease was for a five (5) year term with two separate options to extend for five (5) years each. The City exercised both options, and the second option expired on April 30, 2019. The BBB seeks to reinstate this sublease to prevent any interruption of radio communications, impacting services provided by BBB and other regional transit operators.",
        "Past Council Actions",
        "Meeting Date",
        "Description",
        "September 28, 2004 (attachment A)",
        "Authorization of City Manager to Negotiate and Execute an Amendment to the City’s Agreement with Advanced Electronics for an Antenna Site Lease over a Period of Five Years, with options, for an Amount not to exceed $112,000.",
        "Financial Impacts and Budget Actions",
        "Staff seeks authority to increase the amount of agreement with Bear Communications, Inc. for a lease for an antenna site for Big Blue Bus.",
        "Contract/Agreement/Purchase Order Modification Request",
        "Agreement #",
        "Current Authorized Amount",
        "Modified Request Amount",
        "FY 2018-19 Budget",
        "Dept/CIP Account #",
        "Total Revised Contract Amount",
        "#4553",
        "$326,000",
        "$181,000",
        "C6004770.689000",
        "$507,000",
        "Future funding is contingent upon Council approval."
    ],
    "sponsors": null,
    "meeting_time": 1560299400,
    "agenda_item_id": "3610",
    "agenda": 77
}
```

**Comment by hungrymonkey** [comment]
```
 title: "Approval of Big Blue Bus (BBB) lease extension with Bearcomm for Hollywood Hills Radio Site"
      agenda_item_id: 3610
      department: "Big Blue Bus, Finance & Administrative Services"
      category: "03. Consent Calendar"
      discussion: "BBB implemented an Advanced Fleet Management System (AFMS) in 2003 for transit vehicles that provides Computer Aided Dispatch/Automatic Vehicle Location (CAD/AVL) data.  In support of the AFMS, the City entered into a sublease with Advanced Electronics, the predecessor-in-interest to Bear Communications, Inc. on February 8, 2005 to install radio transponders at the Hollywood Hills antenna site. Currently, the Hollywood Hills antenna site houses BBB’s radio equipment which provides support for the AFMS, voice communication (two-way radio between buses and dispatch), data for real-time signage and customer trip-planning applications such as NextBus, Transit, and Google Transit, and vehicle tracking. BBB utilizes these radio frequencies to communicate with vehicles, collect data to locate and monitor those vehicles, and provide real-time scheduling information to many other transit agencies and systems.  The data provides real-time information to customers on bus arrival information through various applications, providing an advanced customer service experience to the community. The sublease was for a five (5) year term with two separate options to extend for five (5) years each. The City exercised both options, and the second option expired on April 30, 2019. The BBB seeks to reinstate this sublease to prevent any interruption of radio communications, impacting services provided by BBB and other regional transit operators."
      summary: "In 2005, Big Blue Bus (BBB) entered into an agreement with Advanced Electronics, the predecessor-in-interest to Bear Communications, Inc., for the sublease of an antenna site in the Hollywood Hills to install radio transponders to allow BBB to communicate with its vehicles across its service area. The antenna site is the only location available to adequately provide data signals to BBB’s operational systems. Staff recommends that City Council authorize the City Manager to negotiate and execute a second amendment and reinstatement to the Antenna Site Sublease Agreement #4553 with Bear Communications, Inc. for one year with four additional one-year options, and for additional compensation in an amount not to exceed $181,000.  The amount for the first year of the extension would be $32,600. This would result in a 20-year amended agreement with a new total contract amount not to exceed $507,000, with future year funding contingent on Council budget approval. This is a sole source procurement due to Federal Communications Commission (FCC) regulations regarding the BBB’s ability to transmit radio signals."
      url: "http://santamonicacityca.iqm2.com/Citizens/Detail_LegiFile.aspx?Frame=&MeetingID=1183&MediaPosition=&ID=3610&CssClass="
      recommended_actions:
        - "Staff recommends that City Council authorize the City Manager to negotiate and execute a second amendment and reinstatement of agreement #4553 in the amount of $181,000 with Bear Communications, Inc., a California corporation, for extension of an antenna site lease. The change would result in a 20-year amended agreement with a total contract amount not to exceed $507,000, with future year funding contingent on Council budget approval."
```
